Draco-lang/Compiler

- src/Draco.Compiler/Program.cs
- src/Draco.Compiler/Syntax/Lexer.cs
- src/Draco.Compiler/Syntax/TokenType.cs
I added rest of the keywords that are currently specified.
> Added rest of keywords

- src/Draco.Compiler/Program.cs
- src/Draco.Compiler/Syntax/Lexer.cs
- src/Draco.Compiler/Syntax/TokenType.cs
Finished string interpolation and fixed few errors with extended delimeters.
> String Interpolation + some errors fixed

- src/Draco.Compiler/Program.cs
- src/Draco.Compiler/Syntax/Lexer.cs
> line continuations

- src/Draco.Compiler/Syntax/ParseTree.cs
Implement parse tree. Closes #9.
> Parse tree

- .editorconfig
- src/Draco.Compiler/Program.cs
- src/Draco.Compiler/Syntax/Parser.cs
- src/Draco.Compiler/Syntax/TokenSource.cs
Parsing variable declarations is finished and function declaration doesn't parse body and trailing comma is neceseary right now.
> Parsing Declarations

- src/Draco.Compiler/Program.cs
- src/Draco.Compiler/Syntax/Parser.cs
> Parser error recovery

- src/Draco.Compiler.Api/Draco.Compiler.Api.csproj
- src/Draco.Compiler.Api/Scripting/ScriptingEngine.cs
- src/Draco.Compiler.Cli/Program.cs
- src/Draco.Compiler.Internal/Codegen/CSharpCodegen.cs
- src/Draco.Compiler.Internal/Syntax/ParseTree.cs
- src/Draco.Compiler.Internal/Syntax/ParseTreePrinter.cs
- src/Draco.Compiler.Internal/Syntax/Parser.cs
- src/Draco.Compiler.Internal/Syntax/Token.cs
- src/Draco.Compiler.Internal/Utilities/StringUtils.cs
This PR implements code-generation to C# without having type-checking or even symbol-resolution yet. The point is to have something to set up in a playground and then incrementally improve it as we implement semantic steps.
As a side-effect, closes #49 .
> Basic code-generation to C#

- .github/workflows/gh-page-deploy.yml
> Added github action to push Draco.Editor.Web to github pages.

- src/Draco.Compiler.Cli/Program.cs
- src/Draco.Compiler.Internal/Codegen/CSharpCodegen.cs
- src/Draco.Compiler.Internal/Syntax/ParseTree.cs
- src/Draco.Compiler.Internal/Syntax/Parser.cs
- src/Draco.Compiler.Tests/Syntax/ParserTests.cs
Adds more parser tests, closes #53
> More parser tests

- src/Draco.Extension.VsCode/package-lock.json
- src/Draco.Extension.VsCode/package.json
> Added an NPM utility to do the copying

- src/Draco.Compiler.Tests/Syntax/LexerTests.cs
- src/Draco.Compiler.Tests/Syntax/ParserTests.cs
- src/Draco.Compiler/Api/Syntax/TokenType.cs
- src/Draco.Compiler/Internal/Syntax/Lexer.cs
- src/Draco.Compiler/Internal/Syntax/Parser.cs
Adds float literals to the compiler.
> Float literals

- .github/workflows/build.yaml
- .github/workflows/gh-page-deploy.yml
- .github/workflows/tests.yaml
- src/Draco.Compiler.Cli/Draco.Compiler.Cli.csproj
- src/Draco.Compiler.Tests/Draco.Compiler.Tests.csproj
- src/Draco.Compiler/Draco.Compiler.csproj
- src/Draco.Editor.Web/Draco.Editor.Web.csproj
- src/Draco.LanguageServer/Draco.LanguageServer.csproj
- src/Draco.Query.Sample/Draco.Query.Sample.csproj
- src/Draco.Query.Tests/Draco.Query.Tests.csproj
- src/Draco.Query/Draco.Query.csproj
- src/Draco.RedGreenTree.Attributes/Draco.RedGreenTree.Attributes.csproj
- src/Draco.RedGreenTree.Cli/Draco.RedGreenTree.Cli.csproj
- src/Draco.RedGreenTree.SourceGenerator/Draco.RedGreenTree.SourceGenerator.csproj
- src/Draco.RedGreenTree/Draco.RedGreenTree.csproj
Bumped .NET version to 7, switched LangVersion preview to 11.
> .NET 6 => .NET 7

- src/Draco.Editor.Web/app/favicon-downloader.js
- src/Draco.Editor.Web/app/index.html
> Working favicon for the playground

- .github/workflows/build.yaml
- .github/workflows/gh-page-deploy.yml
- .github/workflows/stryker.yaml
- .github/workflows/tests.yaml
- src/Draco.Editor.Web/Program.cs
- src/Draco.Editor.Web/app/build.js
- src/Draco.Editor.Web/app/package-lock.json
- src/Draco.Editor.Web/app/package.json
> Make CI more green.

- src/Draco.Compiler/Internal/Utilities/Option.cs
- src/Draco.Compiler/Internal/Utilities/Result.cs
> Added option type

- src/Draco.Compiler.Tests/Syntax/LexerTests.cs
- src/Draco.Compiler/Api/Syntax/ParseTree.cs
- src/Draco.Compiler/Api/Syntax/TokenType.cs
- src/Draco.Compiler/Api/Syntax/TriviaType.cs
- src/Draco.Compiler/Internal/Syntax/Lexer.cs
- src/Draco.Compiler/Internal/Syntax/ParseTreeFormatter.cs
- src/Draco.Compiler/Internal/Syntax/ParseTreeTransformer.cs
- src/Draco.Compiler/Internal/Syntax/Parser.cs
- src/Draco.Compiler/Internal/Syntax/Token.cs
- src/Draco.Compiler/Internal/Syntax/TokenType.cs
- src/Draco.Compiler/Internal/Syntax/Trivia.cs
Refactored token, so trivia is a separate concept from token.
> Token refactor

- src/Draco.Editor.Web/app/.vscode/extensions.json
- src/Draco.Editor.Web/app/css/app.css
- src/Draco.Editor.Web/app/index.html
- src/Draco.Editor.Web/app/ts/app.ts
> webeditor visual upgrade

- src/Draco.Compiler.Tests/Syntax/LexerTests.cs
- src/Draco.Compiler.Tests/Syntax/ParserTests.cs
- src/Draco.Compiler/Internal/Syntax/Lexer.cs
- src/Draco.Compiler/Internal/Syntax/SyntaxErrors.cs
This PR adds hexadecimal and binary integer notations and scientific floating-point notation.
> Number notations

- src/Draco.Compiler.Cli/Program.cs
- src/Draco.Compiler.Tests/Syntax/ParseTreeFormatterTests.cs
- src/Draco.Compiler/Internal/Syntax/ParseTreeFormatter.cs
Close #172. Other than that, this PR adds `format` command to the cli.
> formater fix

- Getting-Started.md
- README.md
This PR adds getting started guide to the repo.
> Getting started guide

- src/Draco.Compiler.Tests/Semantics/SemanticModelTests.cs
- src/Draco.Compiler.Tests/Semantics/TypeCheckingTests.cs
- src/Draco.Compiler/Api/Semantics/SemanticModel.cs
> Fix SemanticModel cache erasing diagnostics

- src/Draco.Compiler.Tests/EndToEnd/CompilingCodeTests.cs
- src/Draco.Compiler/Internal/Binding/Binder_UntypedExpression.cs
> Multiline string cutoff

- src/Draco.Compiler/Api/Compilation.cs
- src/Draco.LanguageServer/Capabilities/DidDeleteFiles.cs
- src/Draco.LanguageServer/Capabilities/TextDocumentSync.cs
- src/Draco.Lsp/Model/FileDelete.cs
- src/Draco.Lsp/Model/LspModel.xml
- src/Draco.Lsp/Server/Workspace/IDidDeleteFiles.cs
> Fix LSP forgetting to remove deleted source file

- src/Draco.Compiler.Tests/EndToEnd/BclUsageTests.cs
- src/Draco.Compiler.Tests/EndToEnd/CompilingCodeTests.cs
- src/Draco.Compiler.Tests/EndToEnd/Issue139Tests.cs
- src/Draco.Compiler.Tests/Semantics/TypeCheckingTests.cs
- src/Draco.Compiler/Internal/Binding/BinderFacts.cs
- src/Draco.Compiler/Internal/Binding/Binder_UntypedExpression.cs
- src/Draco.Compiler/Internal/Binding/Binder_UntypedLvalue.cs
- src/Draco.Compiler/Internal/Codegen/CilCodegen.cs
- src/Draco.Compiler/Internal/Lowering/LocalRewriter.cs
- src/Draco.Compiler/Internal/OptimizingIr/FunctionBodyCodegen.cs
- src/Draco.Compiler/Internal/OptimizingIr/InstructionFactory.cs
- src/Draco.Compiler/Internal/OptimizingIr/Model/BoxInstruction.cs
- src/Draco.Compiler/Internal/OptimizingIr/ModuleCodegen.cs
- src/Draco.Compiler/Internal/Solver/ConstraintSolver.cs
- src/Draco.Compiler/Internal/Solver/ConstraintSolver_Rules.cs
- src/Draco.Compiler/Internal/Symbols/Metadata/MetadataFieldSymbol.cs
- src/Draco.Compiler/Internal/Symbols/Metadata/MetadataSymbol.cs
Fixes #308 
Fixes #307
Fixes #306
> Crash bug fixes

- src/Draco.Editor.Web/app/build.js
- src/Draco.Editor.Web/app/package-lock.json
- src/Draco.Editor.Web/app/package.json
- src/Draco.Editor.Web/app/ts/cache.ts
- src/Draco.Editor.Web/app/ts/metadata.ts
Added a js dep at build time, this is an esbuild plugin that inject the date at build time in a class.
We could easily write this ourselves, but I have 0 motivation to understand more yet another JS pipeline.
> Added cache invalidation when the playground have a new build.

- scripts/install_debugadapter.ps1
- scripts/install_langserver.ps1
- scripts/install_toolchain.ps1
> Fixed installs scripts.

- .github/workflows/publish.yaml
- src/Draco.DebugAdapter/Draco.DebugAdapter.csproj
- src/Draco.LanguageServer/Draco.LanguageServer.csproj
Made LSP and DAP publish with their respective workflow
> Packaging LSP and DAP

- scripts/install_debugadapter.ps1
- scripts/install_langserver.ps1
- scripts/install_toolchain.ps1
- scripts/install_vscext.ps1
Fixed the vscode extension install script, and added `$ErrorActionPreference = "Stop"` on the installations scripts.
> Fixed VS Code Extension install script,

- src/Draco.Compiler.Tests/Syntax/ParserTests.cs
- src/Draco.Compiler/Api/Syntax/SyntaxFactory.cs
- src/Draco.Compiler/Internal/Syntax/Parser.cs
- src/Draco.Compiler/Internal/Syntax/Syntax.xml
- src/Draco.Compiler/Internal/Syntax/SyntaxErrors.cs
> Import declarations should not accept visibility modifiers.

- src/Draco.Debugger/Debugger.cs
- src/Draco.Debugger/IO/IoWorker.cs
I think we can further refactor this class.
> Refactor IoWorker of debugger. Fixes #336.

- src/Draco.Editor.Web/Draco.Editor.Web.csproj
> Fixed metadata embed ressource on linux.

- src/Draco.Dap/Adapter/Capabilities/IModule.cs
- src/Draco.Dap/Adapter/IDebugClient.cs
- src/Draco.DebugAdapter/DracoDebugAdapter.cs
- src/Draco.DebugAdapter/Translator.cs
- src/Draco.Debugger.Tests/DebuggerTests.cs
- src/Draco.Debugger.Tests/TestDebugSession.cs
- src/Draco.Debugger.Tui/DebuggerWindow.cs
- src/Draco.Debugger.Tui/Program.cs
- src/Draco.Debugger/DebuggerEventHandlers.cs
- src/Draco.Debugger/DebuggerEvents.cs
- src/Draco.Debugger/OnModuleEventArgs.cs
- src/Draco.Extension.VsCode/src/assets.ts
- src/Draco.Lsp/Server/ILanguageClient.cs
Vscode tracing wasn't tested yet.
> Added a simple debugger test plus tracing for debugger in vscode.

- src/Draco.Compiler/Api/Compilation.cs
- src/Draco.Compiler/Api/Syntax/SeparatedSyntaxList.cs
- src/Draco.Compiler/Api/Syntax/SyntaxList.cs
- src/Draco.Compiler/Api/Syntax/SyntaxTree.cs
- src/Draco.Compiler/Internal/Declarations/DeclarationTable.cs
- src/Draco.Compiler/Internal/InterlockedUtils.cs
- src/Draco.Compiler/Internal/Symbols/FunctionSymbol.cs
- src/Draco.Compiler/Internal/Symbols/Generic/FieldInstanceSymbol.cs
- src/Draco.Compiler/Internal/Symbols/Generic/FunctionInstanceSymbol.cs
- src/Draco.Compiler/Internal/Symbols/Generic/GlobalInstanceSymbol.cs
- src/Draco.Compiler/Internal/Symbols/Generic/ParameterInstanceSymbol.cs
- src/Draco.Compiler/Internal/Symbols/Generic/PropertyInstanceSymbol.cs
- src/Draco.Compiler/Internal/Symbols/Metadata/MetadataAssemblySymbol.cs
- src/Draco.Compiler/Internal/Symbols/Metadata/MetadataFieldSymbol.cs
- src/Draco.Compiler/Internal/Symbols/Metadata/MetadataMethodSymbol.cs
- src/Draco.Compiler/Internal/Symbols/Metadata/MetadataPropertySymbol.cs
- src/Draco.Compiler/Internal/Symbols/Metadata/MetadataStaticClassSymbol.cs
- src/Draco.Compiler/Internal/Symbols/Metadata/MetadataStaticFieldSymbol.cs
- src/Draco.Compiler/Internal/Symbols/Metadata/MetadataTypeSymbol.cs
- src/Draco.Compiler/Internal/Symbols/Source/SourceFunctionSymbol.cs
- src/Draco.Compiler/Internal/Symbols/Source/SourceGlobalSymbol.cs
- src/Draco.Compiler/Internal/Symbols/Source/SourceLocalSymbol.cs
- src/Draco.Compiler/Internal/Symbols/Source/SourceModuleSymbol.cs
- src/Draco.Compiler/Internal/Symbols/Source/SourceParameterSymbol.cs
- src/Draco.Compiler/Internal/Symbols/Synthetized/ArrayConstructorSymbol.cs
- src/Draco.Compiler/Internal/Symbols/Synthetized/ConstructorFunctionSymbol.cs
- src/Draco.Compiler/Internal/Symbols/WellKnownTypes.cs
- src/Draco.Compiler/Internal/Syntax/SourceText.cs
- src/Draco.SourceGeneration/Templates/RedSyntaxTree.sbncs
- src/Draco.SourceGeneration/Templates/WellKnownTypes.sbncs
> InterlockedUtils.InitializeNull => LazyInitializer.EnsureInitialized

- src/Draco.Debugger.Tests/DebuggerTests.cs
- src/Draco.Debugger.Tests/IoUtilsTests.cs
- src/Draco.Debugger.Tests/TestDebugSession.cs
- src/Draco.Debugger/Debugger.cs
- src/Draco.Debugger/DebuggerEvents.cs
- src/Draco.Debugger/DebuggerHost.cs
- src/Draco.Debugger/Draco.Debugger.csproj
- src/Draco.Debugger/IO/IoUtils.cs
- src/Draco.Debugger/Platform/IPlatformMethods.cs
- src/Draco.Debugger/Platform/UnixPlatformMethods.cs
- src/Draco.Debugger/Platform/Win32PlatformMethods.cs
Fixed a xplat bug that affect unix&windows, but most of the times unix.  
Reworked the pipes swaps logics so it works on linux, we were leaking a pipe in our process which was the reason it never closed.
> Fix debugger bugs

- .gitignore
- src/Draco.Compiler.Tasks/DracoCompiler.cs
- src/Draco.Compiler.Toolset/build/Draco.Compiler.Toolset.targets
- src/Draco.LanguageServer/Draco.LanguageServer.csproj
- src/Draco.LanguageServer/DracoLanguageServer.cs
- src/Draco.Lsp/Server/ILanguageClient.cs
- src/Draco.ProjectSystem/DesignTimeBuild.cs
- src/Draco.ProjectSystem/Draco.ProjectSystem.csproj
- src/Draco.ProjectSystem/Project.cs
- src/Draco.ProjectSystem/StringWriterLogger.cs
- src/Draco.ProjectSystem/Workspace.cs
Added a basic project system, can be used to read up metadata references
> Basic project system

- src/Draco.Compiler.Tests/EndToEnd/BclUsageTests.cs
- src/Draco.Compiler/Internal/Codegen/CilCodegen.cs
- src/Draco.Compiler/Internal/Symbols/Metadata/MetadataMethodSymbol.cs
Fixes 2 of the most urgent crashes in #429
> Various fixes

- src/Draco.Compiler.Tests/Syntax/LexerTests.cs
- src/Draco.Compiler.Tests/Syntax/ParserTests.cs
- src/Draco.Compiler/Api/Syntax/TokenKind.cs
- src/Draco.Compiler/Internal/Syntax/Lexer.cs
- src/Draco.Compiler/Internal/Syntax/Parser.cs
- src/Draco.Compiler/Internal/Syntax/Syntax.xml
> String escapes

- src/Draco.Compiler/Api/CodeCompletion/CompletionKind.cs
- src/Draco.Compiler/Api/CodeCompletion/CompletionService.cs
- src/Draco.Compiler/Api/CodeCompletion/ExpressionCompletionProvider.cs
- src/Draco.Compiler/Api/CodeCompletion/KeywordCompletionProvider.cs
- src/Draco.Compiler/Api/CodeCompletion/MemberCompletionProvider.cs
- src/Draco.Compiler/Api/Scripting/ReplSession.cs
- src/Draco.Compiler/Api/Syntax/SyntaxTree.cs
- src/Draco.LanguageServer/Translator.cs
- src/Draco.Repl/Configuration.cs
- src/Draco.Repl/ConfigurationDefaults.cs
- src/Draco.Repl/Loop.cs
- src/Draco.Repl/ReplPromptCallbacks.cs
Syntax highlighter, completion
> Repl services

- src/Draco.Compiler.Tests/Syntax/LexerTests.cs
- src/Draco.Compiler.Tests/Syntax/ParserTests.cs
- src/Draco.Compiler/Api/Syntax/SyntaxFacts.cs
- src/Draco.Compiler/Api/Syntax/TokenKind.cs
- src/Draco.Compiler/Internal/Binding/Binder_Expression.cs
- src/Draco.Compiler/Internal/Symbols/FunctionSymbol.cs
- src/Draco.Compiler/Internal/Syntax/Lexer.cs
- src/Draco.Compiler/Internal/Syntax/Parser.cs
- src/Draco.Compiler/Internal/Syntax/Syntax.xml
- src/Draco.Compiler/Internal/Syntax/SyntaxErrors.cs
> C heritage errors (take 2)

- src/Draco.Compiler/Api/Syntax/SeparatedSyntaxList.cs
- src/Draco.Compiler/Api/Syntax/SyntaxList.cs
> Fixed child-parent reation of SyntaxList elements

- .github/workflows/publish.yaml
> Packaging Chr
